# Generated by Django 3.0.3 on 2020-03-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YamlElement',
        ),
    ]
