# Generated by Django 3.0.3 on 2020-03-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_app', '0003_yamlelement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YamlElement',
        ),
    ]
