# Generated by Django 3.0.3 on 2020-03-16 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yaml_app', '0005_yamlelement'),
    ]

    operations = [
        migrations.CreateModel(
            name='YamlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml_app.YamlElement')),
            ],
        ),
    ]
