# Generated by Django 3.0.3 on 2020-03-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
